### PR TITLE
Add Hero background, update image assets, review copys and call to actions

### LINKED ISSUE #8: Background Pattern on Hero
Let's add the background pattern on the Hero. Let's start only adding it there (it's present in other sections, but might be too much :D)

image

### LINKED ISSUE #12: Add git clone box above npx box (until npx is no longer in beta)
At the current state of npx I think we should be a bit conservative and add a box with git clone above the box with npx.

- [ ] Add git clone box. Maybe just with git clone line is enough?  
image
- [ ] Add a daisyui badge with "beta" text to the right of npx box.  Example:
image

### LINKED ISSUE #14: Review website call to actions and copys
Current call to actions and copys are from design phase, we should review and tweak them a bit for the initial version of the website.

### PR DESCRIPTION
**Pull request by Pabl0cks**
## Description

- Added background pattern to Hero section.
- Modified MetaHeader to set a title SEO-friendly and hopefully user-friendly
- Reviewed copys from the different sections and call to actions from buttons.
- Updated Debug Contracts image with the new one created by Andrea, and updated the rest of section images to increase the size from the file, trying to make them look less pixelated in big screens. 
- Also normalized all se2 "sshots" with the `se2SectionName` filename.
- Add git clone box above npx box

Images with the same name get cached during my local tests, is there any way/trick to "force" the system to get the new file without using the cached one?

## Additional Information

- [X] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [X] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Closes #14 
Closes #8 
Closes #12  

Your ENS/address: pabl0cks.eth

### CODE REVIEW

**Comment by Pabl0cks** [comment]
I've just pushed a new commit adding git clone box above npx to fix #12 🙌

**Comment by Pabl0cks** [comment]
Watching the 2 boxes from Hero, I think they would look better with less space between them, right now they look very independant elements, but I think they maybe should be part of the "same element" visually.

It could look like this instead:

image

**Comment by technophile-04** [comment]
Looking great Pablo !! 

>  would look better with less space between them, right now they look very independant elements, but I think they maybe should be part of the "same element" visually

Yeah makes but current changes looks fine too 

Maybe we should add daisy [OR Divider](https://v2.daisyui.com/components/divider/) b/w them ? 

Screenshot 2023-08-06 at 3 40 28 PM


--- 


Also on mobile `git clone ...` doesn't look that great, I don't know what we can do to improve it :(, maybe `text-center` and add some padding to parent container ? 

| Before | After | 
| ------- | ----- | 
| Screenshot 2023-08-06 at 3 54 38 PM |  Screenshot 2023-08-06 at 3 53 04 PM |

**Comment by Pabl0cks** [comment]
Thx for the review and for the suggestions @technophile-04 🙌 I've asked Andrea and she liked it better with the text-center.

How do you see hero like that?

https://www.loom.com/share/3e22c95cb87542ecbd492e5689e13850

**Comment by technophile-04** [comment]
> How do you see hero like that?
> https://www.loom.com/share/3e22c95cb87542ecbd492e5689e13850

Yup this look nice!! 🙌

**Comment by Pabl0cks** [comment]
> Yup this looks nice!! Lets update it 🙌

Cool! Just pushed the change. If you see anything weird in my tailwind styling let me know 🙌

**Comment by technophile-04** [comment]
Tysm Pablo look nice !! 

Just pushed a small change, where instead of adding negative margin to each div instead create a wrapper `div` with `gap-5` so that we get consistent space around "Clone command" - "OR Divider" - "npm Command"

New changes : 


```diff
+ <div className="flex flex-col gap-5 items-center mb-2">
     <CopyToClipboard> 
           ...(Clone command without negative margin)
     </CopyToClipboard>
      <div className="divider px-6 sm:px-20 m-0">OR</div>
      <div className="flex items-center gap-2 mx-2">
         ...(npm command without negative margin)
      </div>
+ </div>
```

Merging this for now 🙌 Lets iterate on different issue, Tysm !!

**Comment by Pabl0cks** [comment]
> Just pushed a small change, where instead of adding negative margin to each div instead create a wrapper div with gap-5 so that we get consistent space around "Clone command" - "OR Divider" - "npm Command"

Thanks @technophile-04 ! Much cleaner 🙌

**Pull request merged**
